### ISSUE TITLE
ConfigMap missing

### ISSUE THREAD

**Issue by styk-tv** [frain-dev/helm-charts#3]
Guys, any chance you could merge latest branch and add a ConfigMap which is referenced in the helm chart.

1. main branch is out of date. latest version on branch is 0.8 (not merged, no merge request)
![image](https://user-images.githubusercontent.com/838921/228893641-1704754c-2e83-4371-82d9-074d5557e526.png)

2. configmap is missing as referenced in the helm chart
https://github.com/frain-dev/helm-charts/blob/release-0.8/charts/convoy/templates/deployment.yaml#L30

**Comment by styk-tv** [comment]
If we come up with a basic structure then it will be easy to convert the config json to a template. I'm looking currently at this folder

https://github.com/frain-dev/convoy/tree/main/config/testdata/Config

to be able to assemble the config as per config map mapping from deployment file here
```
          volumeMounts:
            - name: convoy-config
              mountPath: /config
          command: ["/cmd"]
          args: ["server", "--config", "/config/convoy.json", "-w", "false"]
```

in values.yaml it would be easy to create config section and then keep yaml version of this config directly in values, then have some basic setup and let people know that this yaml is then converted in helmchart to actual json file which is relatively easy to do. that would be an awesome addition to helm chart and would make it work out of the box.

in template you can use function (have not tested)
```
{{ $.Values.config | fromYaml | toJson }}
```

and then your sample configuration could in values file could look like
```
config:
  database:
    dsn: postgres://inside-config-file
  queue:
    type: redis
    redis:
      dsn: redis://localhost:8379
  server:
    http:
      port: 8080
  group:
    strategy:
      type: default
      default:
        intervalSeconds: 125
        retryLimit: 15
    signature:
      hash: SHA256
      header: x-test-signature
    disable_endpoint: true
    replay_attacks: true
  auth:
    require_auth: true
    native:
      enabled: true
    file:
      basic:
      - username: admin
        password: qwerty
        role:
          type: super_user
          group: ''

```

**Comment by jirevwe** [comment]
Hey @styk-tv 

We still run v0.8 on our cloud so we have not gotten around to merging it to main yet. 

I like the suggestion you made, I've never done it like that though. I'll take a look at this.

**Comment by jirevwe** [comment]
Hey @styk-tv

I was able to get this to work using this setup

configmap.yaml
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "convoy.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "convoy.name" . }}
    helm.sh/chart: {{ include "convoy.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  convoy.json: {{ toJson .Values.config | quote }}
```

values.yaml
```yaml
config:
  {
    "host": "http://localhost:5005",
    "database":
      {
        "type": "postgres",
        "dsn": "postgres://postgres:postgres@localhost/convoy",
      },
    "cache": { "type": "redis", "redis": { "dsn": "redis://localhost:6379" } },
    "queue": { "type": "redis", "redis": { "dsn": "redis://localhost:6379" } },
    "smtp":
      {
        "provider": "sendgrid",
        "url": "smtp.sendgrid.net",
        "port": 2525,
        "username": "username",
        "password": "password",
        "from": "e@mail.com",
      },
    "server": { "http": { "port": 5005, "worker_port": 5006 } },
    "disable_endpoint": false,
    "auth": { "native": { "enabled": true }, "jwt": { "enabled": true } },
  }
```

Still testing it out, I'll let you know when I have pushed the changes
