### ISSUE TITLE
Stream, Worker, and Server Child Charts Have Identical Cmd Args That Deviate From docker-compose.yml

### ISSUE THREAD

**Issue by shin-go** [frain-dev/helm-charts#9]
Comparing the `docker-compose.yml` provided in the convoy repo against the `cmd` and `args` config for the Stream, Worker, and Server components (child charts), there's a clear difference in configuration. For example, all three components are configured like this in their `deployment.yaml` templates:

```
...
  containers:
    - name: convoy-server
      image: docker.cloudsmith.io/convoy/convoy/frain-dev/convoy:v0.9.2
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - name: convoy-config
          mountPath: /config
      command: ["/cmd"]
      args: ["server", "--config", "/config/convoy.json", "-w", "false"]
...
```
and
```
...
containers:
  - name: convoy-stream
    image: docker.cloudsmith.io/convoy/convoy/frain-dev/convoy:v0.9.2
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - name: convoy-config
        mountPath: /config
    command: ["/cmd"]
    args: ["server", "--config", "/config/convoy.json", "-w", "false"]
...
```

Whereas the `docker-compose.yml` has each component configured like this:
```
worker:
  image: docker.cloudsmith.io/convoy/convoy/frain-dev/convoy:v0.9.2
  command: ["./cmd", "worker", "--config", "convoy.json"]
...
stream:
  image: docker.cloudsmith.io/convoy/convoy/frain-dev/convoy:v0.9.2
  command: ["./cmd", "stream", "--config", "convoy.json"]
...
```
The `--config` value being different aside, there's clearly a difference in what arg each component is running with from my examples taken from the child helm charts - notably in stream's case where it's also being started up with the `worker` arg.

If the `docker-compose.yml` is the basis for the `cmd` and `args` config for each component, the helm charts should be consistent to that.
